name: Build Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-explorer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Explorer/Dockerfile --tag naamitest/explorer:$RELEASE_VERSION
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: naamitest
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Publish Docker Image
      run: docker push naamitest/explorer:$RELEASE_VERSION