name: Publish NuGet Packages 

on:
  push:
    tags:
      - '*'

jobs:
  publish-suinet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Dotnet Restore MoveBinaryReader
      run: dotnet restore ./MoveBinaryReader/
    - name: Build MoveBinaryReader
      run: dotnet build ./MoveBinaryReader/ --configuration Release -p:VersionPrefix=$RELEASE_VERSION
    - name: Pack MoveBinaryReader
      run: dotnet pack ./MoveBinaryReader/ --configuration Release -p:VersionPrefix=$RELEASE_VERSION
    - name: Publish Nuget nuget.org  (MoveBinaryReader)
      run: dotnet nuget push "./MoveBinaryReader/bin/Release/MoveBinaryReader.$RELEASE_VERSION.nupkg" --api-key ${{ secrets.NUGET_PAT }} --source "nuget"